### ISSUE TITLE
crediting others

### ISSUE THREAD

**Issue by siren15** [warung-international/peradaban#2]
Hey mate, it would be really nice if you credited people if you use their code. Like for example me when using a good chunk from my bot, or others as well.

**Comment by SanityZeroPercent** [comment]
Hi there,

Thanks for the tip,  I'm so sorry if i didn't give credits to you and other code i take reference on.

I may be forgot to double check the credits on some file. I usually put the credits on `line 1` of each file.

I'll double check it later, since i kinda busy irl.

Again, I'm so sorry. 🙏

Thanks.

**Comment by siren15** [comment]
Np, we all can forget to do some things, just wanted to make sure it's not forgotten, thanks tho.

**Comment by SanityZeroPercent** [comment]
Hey @siren15, Sorry to bother you.

Just a follow up, I've added the credits into this repository readme. 

Again, Thanks for the heads up and have a nice day! :3
